// src/routes/agb/+page.svelte
<script lang="ts">
    // AGB - Allgemeine Geschäftsbedingungen (Terms and Conditions)
</script>

<svelte:head>
    <title>AGB | Aust Umzüge Hildesheim</title>
    <meta
        name="description"
        content="Allgemeine Geschäftsbedingungen (AGB) von Aust Umzüge und Haushaltsauflösungen in Hildesheim."
    />
</svelte:head>

<main class="agb">
    <div class="agb__container">
        <h1 class="agb__heading">Allgemeine Geschäftsbedingungen</h1>

        <section class="agb__section">
            <h2>1. Beauftragen eines weiteren Frachtführers</h2>
            <p>
                Der Möbelspediteur kann einen weiteren Frachtführer zur
                Durchführung des Umzuges heranziehen.
            </p>
        </section>

        <section class="agb__section">
            <h2>2. Zusatzleistungen</h2>
            <p>
                Der Möbelspediteur führt unter Wahrung des Interesses des
                Absenders seine Verpflichtungen mit der verkehrsüblichen
                Sorgfalt eines ordentlichen Möbelspediteurs gegen Zahlung des
                vereinbarten Entgelts aus. Zusätzlich zu vergüten sind
                besondere, bei Vertragsabschluss nicht vorhersehbare Leistungen
                und Aufwendungen. Gleiches gilt, wenn der Leistungsumfang durch
                den Absender nach Vertragsabschluss erweitert wird.
            </p>
        </section>

        <section class="agb__section">
            <h2>3. Kündigung des Vertrages</h2>
            <p>
                Die Vertragskündigung bedarf der Schriftform. Bei einer
                Kündigung ohne wichtigen Grund wird eine Rücktrittszahlung von
                30% des veranschlagten Entgelts erhoben. Ab 3 Tage vor
                Auftragstermin ist eine Kündigung nicht mehr möglich. Es wird
                der Gesamtbruttopreis in Rechnung gestellt. Bei einem Auftrag
                auf Stundenbasis werden in diesen Fällen 8 Stunden berechnet.
            </p>
        </section>

        <section class="agb__section">
            <h2>4. Trinkgelder</h2>
            <p>
                Trinkgelder sind mit der Rechnung des Möbelspediteurs nicht
                verrechenbar.
            </p>
        </section>

        <section class="agb__section">
            <h2>5. Erstattung der Umzugskosten</h2>
            <p>
                Soweit der Absender gegenüber einer Dienststelle oder einem
                Arbeitgeber einen Anspruch auf Umzugskostenvergütung hat, weist
                er diese Stelle an, die vereinbarte und fällige
                Umzugskostenvergütung abzüglich geleisteter Anzahlungen oder
                Teilzahlungen auf entsprechende Anforderung direkt an den
                Möbelspediteur auszuzahlen.
            </p>
        </section>

        <section class="agb__section">
            <h2>6. Transportsicherungen</h2>
            <p>
                Der Absender ist verpflichtet, bewegliche oder elektronische
                Teile an hochempfindlichen Geräten wie z.B. Waschmaschinen,
                Plattenspielern, Fernseh-, Radio- und HiFi-Geräten, EDV Anlagen
                fachgerecht für den Transport sichern zu lassen. Zur Überprüfung
                der fachgerechten Sicherung ist der Möbelspediteur nicht
                verpflichtet.
            </p>
        </section>

        <section class="agb__section">
            <h2>7. Elektro- und Installationsarbeiten</h2>
            <p>
                Die Mitarbeiter des Möbelspediteurs sind, sofern nicht anders
                vereinbart ist, nicht zur Vornahme von Elektro-, Gas-, Dübel-
                und sonstigen Installationsarbeiten berechtigt.
            </p>
        </section>

        <section class="agb__section">
            <h2>8. Handwerkervermittlung</h2>
            <p>
                Bei Leistungen zusätzlich vermittelter Handwerker haftet der
                Möbelspediteur nur für die sorgfältige Auswahl.
            </p>
        </section>

        <section class="agb__section">
            <h2>9. Aufrechnung</h2>
            <p>
                Gegen Ansprüche des Möbelspediteurs ist eine Aufrechnung nur mit
                fälligen Gegenansprüchen zulässig, die unbestritten oder
                rechtskräftig festgestellt sind.
            </p>
        </section>

        <section class="agb__section">
            <h2>10. Abtretung</h2>
            <p>
                Der Möbelspediteur ist auf Verlangen der Ersatzberechtigten
                verpflichtet, die ihm aus dem von ihm abzuschließenden
                Versicherungsvertrag zustehenden Rechte an den
                Ersatzberechtigten abzutreten.
            </p>
        </section>

        <section class="agb__section">
            <h2>11. Missverständnisse</h2>
            <p>
                Die Gefahr des Missverständnisses anderer als schriftlicher
                Auftragsbestätigungen, Weisungen und Mitteilungen des Absenders
                und solche an andere zu ihrer Annahme nicht bevollmächtigte
                Leute des Möbelspediteurs hat der letztere nicht zu
                verantworten.
            </p>
        </section>

        <section class="agb__section">
            <h2>12. Nachprüfung durch den Absender</h2>
            <p>
                Bei der Abholung des Umzugsgutes ist der Absender verpflichtet,
                nachzuprüfen, dass kein Gegenstand oder keine Einrichtung
                irrtümlich mitgenommen oder stehen gelassen wird.
            </p>
        </section>

        <section class="agb__section">
            <h2>13. Fälligkeit des vereinbarten Entgelts</h2>
            <p>
                Der Betrag ist bei Transporten innerhalb Deutschlands nach dem
                Verladen fällig und in bar oder in Form gleichwertiger
                Zahlungsmittel zu bezahlen. Bei Auslandstransporten gelten
                dieselben Regelungen wie bei Inlandstransporten. Barauslagen in
                ausländischer Währung sind nach dem abgerechneten Wechselkurs zu
                entrichten. Kommt der Auftraggeber seiner Zahlungspflicht nicht
                nach, ist der Möbelspediteur berechtigt, das Umzugsgut
                anzuhalten oder nach Beginn der Beförderung auf Kosten des
                Auftraggebers einzulagern, gemäß § 419 HGB.
            </p>
        </section>

        <section class="agb__section">
            <h2>14. Gerichtsstand</h2>
            <p>
                Für Rechtsstreitigkeiten mit Vollkaufleuten auf Grund dieses
                Vertrages und über Ansprüche aus anderen Rechtsgründen, die mit
                dem Transportauftrag zusammenhängen, ist das Gericht, in dessen
                Bezirk sich die vom Absender beauftragte Niederlassung des
                Möbelspediteurs befindet, ausschließlich zuständig. Für
                Rechtsstreitigkeiten mit anderen als Vollkaufleuten gilt die
                ausschließliche Zuständigkeit nur für den Fall, dass der
                Absender nach Vertragsabschluss seinen Wohnsitz oder
                gewöhnlichen Aufenthaltsort in das Ausland verlegt oder sein
                Wohnsitz oder persönlicher Aufenthaltsort zum Zeitpunkt der
                Klageerhebung nicht bekannt ist.
            </p>
        </section>

        <section class="agb__section">
            <h2>15. Haftungsbedingungen</h2>

            <div class="agb__info-box">
                <h3>HAFTUNGSINFORMATION</h3>
                <p>Des Möbelspediteurs gemäß § 451g HGB</p>
            </div>

            <h3>Anwendungsbereich</h3>
            <p>
                Der Frachtführer (im folgenden Möbelspediteur genannt) haftet
                nach dem Umzugsvertrag und dem Handelsgesetzbuch (HGB). Für
                Beförderungen von Umzugsgut von und nach Orten außerhalb
                Deutschlands finden dieselben Haftungsgrundsätze Anwendung. Dies
                gilt auch, wenn verschiedenartige Beförderungsmittel zum Einsatz
                kommen.
            </p>

            <h3>Haftungsgrundsätze</h3>
            <p>
                Der Möbelspediteur haftet für den Schaden, der durch Verlust
                oder Beschädigung des Umzugsgutes in der Zeit von der Übernahme
                zur Beförderung bis zur Ablieferung oder durch Überschreitung
                der Lieferfrist entsteht (Obhutshaftung).
            </p>

            <h3>Haftungshöchstbetrag</h3>
            <p>
                Die Haftung des Möbelspediteurs wegen Verlust oder Beschädigung
                ist auf einen Betrag von € 620,00 je Kubikmeter Laderaum, der zu
                Erfüllung des Vertrages benötigt wird beschränkt. Wegen
                Überschreitung der Lieferfrist ist die Haftung des
                Möbelspediteurs auf den dreifachen Betrag der Fracht begrenzt.
                Haftet der Möbelspediteur wegen der Verletzung einer mit der
                Ausführung des Umzuges zusammenhängenden vertraglichen Pflicht
                für Schäden, die nicht durch den Verlust oder Beschädigung des
                Umzugsgutes oder durch Überschreiten der Lieferfrist entstehen,
                und handelt es sich um andere Schäden als Sach- und
                Personenschäden so ist in diesem Fall die Haftung auf das
                Dreifache des Betrages begrenzt, der bei Verlust des Gutes zu
                zahlen wäre.
            </p>

            <h3>Wertersatz</h3>
            <p>
                Hat der Möbelspediteur Schadenersatz zu leisten, so ist der Wert
                am Ort und zur Zeit der Übernahme zur Beförderung zu ersetzen.
                Der Wert des Umzugsgutes bestimmt sich in der Regel nach dem
                Marktpreis. Zusätzlich sind alle Kosten der Schadensfeststellung
                zu ersetzen.
            </p>

            <h3>Haftungsausschluss</h3>
            <p>
                Der Möbelspediteur ist von der Haftung befreit soweit der
                Verlust, die Beschädigung oder die Überschreitung der
                Lieferfrist auf Umständen beruht, die der Möbelspediteur auch
                bei größter Sorgfalt nicht vermeiden und deren Folgen er nicht
                abwenden konnte (unabwendbares Ereignis).
            </p>

            <h3>Besondere Haftungsausschlussgründe</h3>
            <p>
                Der Möbelspediteur ist von seiner Haftung befreit, soweit der
                Verlust oder die Beschädigung auf eine der folgenden Gefahren
                zurückzuführen ist:
            </p>
            <ol>
                <li>
                    Beförderung von Edelmetallen, Juwelen, Edelsteinen, Geld,
                    Briefmarken, Münzen, Wertpapiere oder Urkunden
                </li>
                <li>
                    Ungenügende Verpackung oder Kennzeichnung durch den Absender
                </li>
                <li>
                    Behandeln, Verladen oder Entladen des Umzugsgutes durch den
                    Absender
                </li>
                <li>
                    Beförderung von nicht vom Möbelspediteur verpacktem Gut in
                    Behältern
                </li>
                <li>
                    Verladen oder Entladen von Umzugsgut, dessen Größe oder
                    Gewicht den Raumverhältnissen an der Ladestelle oder
                    Entladestelle nicht entspricht, sofern der Möbelspediteur
                    den Absender auf die Gefahr einer Beschädigung vorher
                    hingewiesen und der Absender auf die Durchführung der
                    Leistung bestanden hat
                </li>
                <li>Beförderung lebender Tiere und Pflanzen</li>
                <li>
                    Natürliche oder mangelhafte Beschaffenheit des Umzugsgutes,
                    der zufolge es besonders leicht Schäden, insbesondere durch
                    Bruch, Funktionsstörungen, Rost, inneren Verderb oder
                    Auslaufen erleidet
                </li>
            </ol>
            <p>
                Der Möbelspediteur kann sich auf die besonderen
                Haftungsausschlussgründe nur berufen, wenn er alle nach den
                Umständen obliegenden Maßnahmen getroffen und besondere
                Weisungen beachtet hat.
            </p>

            <h3>Außervertragliche Ansprüche</h3>
            <p>
                Die Haftungsbefreiung und Haftungsbegrenzungen gelten auch für
                einen außervertraglichen Anspruch des Absenders oder des
                Empfängers gegen den Möbelspediteur wegen Verlust oder
                Beschädigung des Umzugsgutes oder wegen Überschreitung der
                Lieferfrist.
            </p>

            <h3>Wegfall der Haftungsbefreiungen und -Begrenzungen</h3>
            <p>
                Die Haftungsbefreiungen und Haftungsbegrenzungen gelten nicht,
                wenn der Schaden auf eine Handlung oder Unterlassung
                zurückzuführen ist, die der Möbelspediteur vorsätzlich oder
                leichtfertig und in dem Bewusstsein, dass ein Schaden mit
                Wahrscheinlichkeit eintreten werde, begangen hat.
            </p>

            <h3>Haftung der Leute</h3>
            <p>
                Werden Schadenersatzansprüche aus außervertraglicher Haftung
                wegen Verlust oder Beschädigung des Umzugsgutes oder wegen
                Überschreitung der Lieferfrist gegen einen der Leute des
                Möbelspediteurs erhoben, so kann sich auch jener auf die
                Haftungsbefreiungen und -begrenzungen berufen. Das gilt auch,
                wenn er vorsätzlich oder leichtfertig und in dem Bewusstsein,
                dass ein Schaden mit Wahrscheinlichkeit eintreten werde,
                gehandelt hat.
            </p>

            <h3>Ausführender Möbelspediteur</h3>
            <p>
                Wird der Umzug ganz oder teilweise durch einen Dritten
                ausgeführt (ausführender Möbelspediteur), so haftet dieser für
                den Schaden, der durch den Verlust oder Beschädigung des Gutes
                oder durch Überschreitung der Lieferfrist während der durch ihn
                ausgeführten Beförderung entsteht, in gleicher Weise wie der
                Möbelspediteur. Der ausführende Möbelspediteur kann alle
                Einwendungen geltend machen, die dem Möbelspediteur aus dem
                Frachtvertrag zustehen. Möbelspediteur und ausführender
                Möbelspediteur haften als Gesamtschuldner. Werden Leute des
                ausführenden Möbelspediteurs in Anspruch genommen, so gelten für
                diese die Bestimmungen über Haftung der Leute.
            </p>

            <h3>Haftungsvereinbarung</h3>
            <p>
                Der Möbelspediteur weist den Absender auf die Möglichkeit hin,
                mit ihm gegen Bezahlung eines entsprechenden Entgeltes eine
                weitergehende als die gesetzlich vorgesehene Haftung zu
                vereinbaren.
            </p>

            <h3>Transportversicherung</h3>
            <p>
                Der Möbelspediteur weist den Absender auf die Möglichkeit hin,
                das Gut gegen Bezahlung einer besonderen Prämie zu versichern.
            </p>

            <h3>Schadensanzeige</h3>
            <p>
                Um das Erlöschen von Ersatzansprüchen zu verhindern, ist
                folgendes zu beachten:
            </p>
            <ul>
                <li>
                    Der Absender ist verpflichtet, das Gut sofort bei
                    Ablieferung auf äußerlich erkennbare Beschädigungen oder
                    Verlust zu untersuchen.
                </li>
                <li>
                    Diese sind auf dem Ablieferungsbeleg oder einem
                    Schadensprotokoll spezifiziert festzuhalten und dem
                    Möbelspediteur spätestens am Tag nach der Ablieferung
                    anzuzeigen.
                </li>
                <li>
                    Äußerlich nicht erkennbare Beschädigungen oder Verluste, die
                    der Absender erst beim Auspacken des Umzugsgutes feststellt,
                    müssen dem Möbelspediteur innerhalb 14 Tagen nach
                    Ablieferung spezifiziert angezeigt werden.
                </li>
                <li>Pauschale Schadenanzeige genügen in keinem Fall.</li>
                <li>
                    Ansprüche wegen Überschreitung der Lieferfrist erlöschen
                    wenn der Empfänger dem Möbelspediteur die Überschreitung
                    nicht innerhalb von 14 Tagen nach Ablieferung anzeigt.
                </li>
            </ul>
            <p>
                Wird eine Anzeige nach Ablieferung erstattet, muss sie – um den
                Anspruchsverlust zu verhindern – in jedem Fall in schriftlicher
                Form und innerhalb der vorgesehenen Fristen erfolgen. Zur
                Wahrung der Fristen genügt die rechtzeitige Absendung.
            </p>

            <h3>Gefährliches Umzugsgut</h3>
            <p>
                Zählt zu dem Umzugsgut gefährliches Gut (z.B. Benzin oder Öle),
                ist der Absender verpflichtet, dem Möbelspediteur rechtzeitig
                anzugeben welcher Natur die Gefahr ist, die von dem Gut ausgeht
                (z. B. Feuergefährlichkeit, ätzender Flüssigkeit, explosive
                Stoffe etc.).
            </p>
        </section>

        <section class="agb__section">
            <h2>16. Rechtswahl</h2>
            <p>Es gilt deutsches Recht.</p>
        </section>

        <section class="agb__section">
            <p>
                Bitte beachten Sie auch unser <a href="/impressum">Impressum</a>
                und unsere <a href="/datenschutz">Datenschutzerklärung</a>.
            </p>
        </section>
    </div>
</main>

<style>
    .agb {
        padding-block: var(--space-16);
        background-color: var(--color-text);
        min-height: 60vh;
    }

    .agb__container {
        max-width: 800px;
        margin-inline: auto;
        padding-inline: var(--container-padding);
    }

    .agb__heading {
        color: var(--color-info-bar);
        font-size: clamp(var(--text-3xl), 5vw, var(--text-5xl));
        font-weight: var(--font-bold);
        margin: 0 0 var(--space-10);
        position: relative;
        padding-bottom: var(--space-4);
    }

    .agb__heading::after {
        content: "";
        position: absolute;
        left: 0;
        bottom: 0;
        width: 80px;
        height: 4px;
        background: linear-gradient(90deg, var(--color-nav-accent), #ff8a3d);
        border-radius: var(--radius-full);
    }

    .agb__section {
        margin-bottom: var(--space-8);
    }

    .agb__section h2 {
        color: var(--color-info-bar);
        font-size: var(--text-lg);
        font-weight: var(--font-bold);
        margin: 0 0 var(--space-3);
    }

    .agb__section h3 {
        color: var(--color-info-bar);
        font-size: var(--text-base);
        font-weight: var(--font-semibold);
        margin: var(--space-5) 0 var(--space-2);
    }

    .agb__section p {
        color: #4a5568;
        font-size: var(--text-base);
        line-height: 1.75;
        margin: 0 0 var(--space-3);
    }

    .agb__section ul,
    .agb__section ol {
        color: #4a5568;
        font-size: var(--text-base);
        line-height: 1.75;
        margin: 0 0 var(--space-4);
        padding-left: var(--space-6);
    }

    .agb__section li {
        margin-bottom: var(--space-2);
    }

    .agb__section a {
        color: var(--color-nav-accent);
        text-decoration: none;
        transition: color var(--transition-fast);
    }

    .agb__section a:hover {
        color: #d84a00;
        text-decoration: underline;
    }

    .agb__info-box {
        background-color: var(--color-info-bar);
        color: var(--color-text);
        padding: var(--space-4) var(--space-6);
        border-radius: var(--radius-md);
        margin-bottom: var(--space-6);
    }

    .agb__info-box h3 {
        color: var(--color-text);
        font-size: var(--text-lg);
        font-weight: var(--font-bold);
        margin: 0 0 var(--space-2);
    }

    .agb__info-box p {
        color: rgba(255, 255, 255, 0.9);
        margin: 0;
    }

    @media (max-width: 767px) {
        .agb {
            padding-block: var(--space-10);
        }

        .agb__section {
            margin-bottom: var(--space-6);
        }
    }
</style>

// aust-new-next-main/src/app/agb/page.tsx
import type { Metadata } from 'next';
import styles from './agb.module.css';

export const metadata: Metadata = {
  title: "Unsere AGB | Aufraeumhelden",
  description: "Lesen Sie unsere Allgemeinen Geschäftsbedingungen für Umzüge und Haushaltsauflösungen.",
};

const AgbPage = () => {
  return (
    <div className={styles['impressum-container']}>
      <div className={styles['disclaimer-section']}>
        <h2 className={styles.heading2}>Unsere AGB</h2>
        <div className={styles['disclaimer-text']}>
          <p>1. Beauftragen eines weiteren Frachtführers<br />
            Der Möbelspediteur kann einen weiteren Frachtführer zur Durchführung des Umzuges heranziehen.</p>
          <p>2. Zusatzleistungen<br />
            Der Möbelspediteur führt unter Wahrung des Interesses des Absenders seine Verpflichtungen mit der verkehrsüblichen Sorgfalt eines ordentlichen Möbelspediteurs gegen Zahlung des vereinbarten Entgelts aus. Zusätzlich zu vergüten sind besondere, bei Vertragsabschluss nicht vorhersehbare Leistungen und Aufwendungen. Gleiches gilt, wenn der Leistungsumfang durch den Absender nach Vertragsabschluss erweitert wird.</p>
          <p>3. Kündigung des Vertrages<br />
            Die Vertragskündigung bedarf der Schriftform. Bei einer Kündigung ohne wichtigen Grund wird eine Rücktrittszahlung von 30% des veranschlagten Entgelts erhoben. Ab 3 Tage vor Auftragstermin ist eine Kündigung nicht mehr möglich. Es wird der Gesamtbruttopreis in Rechnung gestellt. Bei einem Auftrag auf Stundenbasis werden in diesen Fällen 8 Stunden berechnet.</p>
          <p>4. Trinkgelder<br />
            Trinkgelder sind mit der Rechnung des Möbelspediteurs nicht verrechenbar.</p>
          <p>5. Erstattung der Umzugskosten<br />
            Soweit der Absender gegenüber einer Dienststelle oder einem Arbeitgeber einen Anspruch auf Umzugskostenvergütung hat, weist er diese Stelle an, die vereinbarte und fällige Umzugskostenvergütung abzüglich geleisteter Anzahlungen oder Teilzahlungen auf entsprechende Anforderung direkt an den Möbelspediteur auszuzahlen.</p>
          <p>6. Transportsicherungen<br />
            Der Absender ist verpflichtet, bewegliche oder elektronische Teile an hochempfindlichen Geräten wie z.B. Waschmaschinen, Plattenspielern, Fernseh-, Radio- und HiFi-Geräten, EDV Anlagen fachgerecht für den Transport sichern zu lassen. Zur Überprüfung der fachgerechten Sicherung ist der Möbelspediteur nicht verpflichtet.</p>
          <p>7. Elektro- und Installationsarbeiten<br />
            Die Mitarbeiter des Möbelspediteurs sind, sofern nicht anders vereinbart ist, nicht zur Vornahme von Elektro-, Gas-, Dübel- und sonstigen Installationsarbeiten berechtigt.</p>
          <p>8. Handwerkervermittlung<br />
            Bei Leistungen zusätzlich vermittelter Handwerker haftet der Möbelspediteur nur für die sorgfältige Auswahl.</p>
          <p>9. Aufrechnung<br />
            Gegen Ansprüche des Möbelspediteurs ist eine Aufrechnung nur mit fälligen Gegenansprüchen zulässig, die unbestritten oder rechtskräftig festgestellt sind.</p>
          <p>10. Abtretung<br />
            Der Möbelspediteur ist auf Verlangen der Ersatzberechtigten verpflichtet, die ihm aus dem von ihm abzuschließenden Versicherungsvertrag zustehenden Rechte an den Ersatzberechtigten abzutreten.</p>
          <p>11. Missverständnisse<br />
            Die Gefahr des Missverständnisses anderer als schriftlicher Auftragsbestätigungen, Weisungen und Mitteilungen des Absenders und solche an andere zu ihrer Annahme nicht bevollmächtigte Leute des Möbelspediteurs hat der letztere nicht zu verantworten.</p>
          <p>12. Nachprüfung durch den Absender<br />
            Bei der Abholung des Umzugsgutes ist der Absender verpflichtet, nachzuprüfen, dass kein Gegenstand oder keine Einrichtung irrtümlich mitgenommen oder stehen gelassen wird.</p>
          <p>13. Fälligkeit des vereinbarten Entgelts<br />
            Der Betrag ist bei Transporten innerhalb Deutschlands nach dem Verladen fällig und in bar oder in Form gleichwertiger Zahlungsmittel zu bezahlen. Bei Auslandstransporten gelten dieselben Regelungen wie bei Inlandstransporten. Barauslagen in ausländischer Währung sind nach dem abgerechneten Wechselkurs zu entrichten. Kommt der Auftraggeber seiner Zahlungspflicht nicht nach, ist der Möbelspediteur berechtigt, das Umzugsgut anzuhalten oder nach Beginn der Beförderung auf Kosten des Auftraggebers einzulagern, gemäß § 419 HGB.</p>
          <p>14. Gerichtsstand<br />
            Für Rechtsstreitigkeiten mit Vollkaufleuten auf Grund dieses Vertrages und über Ansprüche aus anderen Rechtsgründen, die mit dem Transportauftrag zusammenhängen, ist das Gericht, in dessen Bezirk sich die vom Absender beauftragte Niederlassung des Möbelspediteurs befindet, ausschließlich zuständig. Für Rechtsstreitigkeiten mit anderen als Vollkaufleuten gilt die ausschließliche Zuständigkeit nur für den Fall, dass der Absender nach Vertragsabschluss seinen Wohnsitz oder gewöhnlichen Aufenthaltsort in das Ausland verlegt oder sein Wohnsitz oder persönlicher Aufenthaltsort zum Zeitpunkt der Klageerhebung nicht bekannt ist.</p>
          <p>15. Haftungsbedingungen<br />
            HAFTUNGSINFORMATION<br />
            Des Möbelspediteurs gemäß § 451g HGB</p>
          <p>Anwendungsbereich:<br />
            Der Frachtführer (im folgenden Möbelspediteur genannt) haftet nach dem Umzugsvertrag und dem Handelsgesetzbuch (HGB). Für Beförderungen von Umzugsgut von und nach Orten außerhalb Deutschlands finden dieselben Haftungsgrundsätze Anwendung. Dies gilt auch, wenn verschiedenartige Beförderungsmittel zum Einsatz kommen.</p>
          <p>Haftungsgrundsätze:<br />
            Der Möbelspediteur haftet für den Schaden, der durch Verlust oder Beschädigung des Umzugsgutes in der Zeit von der Übernahme zur Beförderung bis zur Ablieferung oder durch Überschreitung der Lieferfrist entsteht (Obhutshaftung)</p>
          <p>Haftungshöchstbetrag:<br />
            Die Haftung des Möbelspediteurs wegen Verlust oder Beschädigung ist auf einen Betrag von € 620,00 je Kubikmeter Laderaum, der zu Erfüllung des Vertrages benötigt wird beschränkt. Wegen Überschreitung der Lieferfrist ist die Haftung des Möbelspediteurs auf den dreifachen Betrag der Fracht begrenzt. Haftet der Möbelspediteur wegen der Verletzung einer mit der Ausführung des Umzuges zusammenhängenden vertraglichen Pflicht für Schäden, die nicht durch den Verlust oder
            Beschädigung des Umzugsgutes oder durch Überschreiten der Lieferfrist entstehen, und handelt es sich um andere Schäden als Sach- und Personenschäden so ist in diesem Fall die Haftung auf das Dreifache des Betrages begrenzt, der bei Verlust des Gutes zu zahlen wäre.</p>
          <p>Wertersatz:<br />
            Hat der Möbelspediteur Schadenersatz zu leisten, so ist der Wert am Ort und zur Zeit der Übernahme zur Beförderung zu ersetzen. Der Wert des Umzugsgutes bestimmt sich in der Regel nach dem Marktpreis. Zusätzlich sind alle Kosten der Schadensfeststellung zu ersetzen.</p>
          <p>Haftungsausschluss:<br />
            Der Möbelspediteur ist von der Haftung befreit soweit der Verlust, die Beschädigung oder die Überschreitung der Lieferfrist auf Umständen beruht, die der Möbelspediteur auch bei größter Sorgfalt nicht vermeiden und deren Folgen er nicht abwenden konnte (unabwendbares Ereignis)</p>
          <p>Besondere Haftungsausschlussgründe:<br />
            Der Möbelspediteur ist von seiner Haftung befreit, soweit der Verlust oder die Beschädigung auf eine der folgenden Gefahren zurückzuführen ist: 1. Beförderung von Edelmetallen, Juwelen, Edelsteinen, Geld, Briefmarken, Münzen, Wertpapiere oder Urkunden 2. Ungenügende Verpackung oder Kennzeichnung durch den Absender 3. Behandeln, Verladen oder Entladen des Umzugsgutes durch den Absender 4. Beförderung von nicht vom Möbelspediteur verpacktem Gut in Behältern; 5. Verladen oder Entladen von Umzugsgut, dessen Größe oder Gewicht den Raumverhältnissen an der Ladestelle oder Entladestelle nicht entspricht, sofern der Möbelspediteur den Absender auf die Gefahr einer Beschädigung vorher hingewiesen und der Absender auf die Durchführung der Leistung bestanden hat. 6. Beförderung lebender Tiere und Pflanzen 7. Natürliche oder mangelhafte Beschaffenheit des Umzugs gutes, der zufolge es besonders leicht Schäden, insbesondere durch Bruch, Funktionsstörungen, Rost, inneren Verderb oder Auslaufen erleidet. Der Möbelspediteur kann sich auf die besonderen Haftungsausschluss gründe nur berufen, wenn er alle nach den Umständen obliegenden Maßnahmen getroffen und besondere Weisungen beachtet hat.</p>
          <p>Außervertragliche Ansprüche:<br />
            Die Haftungsbefreiung und Haftungsbegrenzungen gelten auch für einen außervertraglichen Anspruch des Absenders oder des Empfängers gegen den Möbelspediteur wegen Verlust oder Beschädigung des Umzugsgutes oder wegen Überschreitung der Lieferfrist.</p>
          <p>Wegfall der Haftungsbefreiungen und – Begrenzungen:<br />
            Die Haftungsbefreiungen und Haftungsbegrenzungen gelten nicht, wenn der Schaden auf eine Handlung oder Unterlassung zurückzuführen ist, die der Möbelspediteur vorsätzlich oder leichtfertig und in dem Bewusstsein, dass ein Schaden mit Wahrscheinlichkeit eintreten werde, begangen hat.</p>
          <p>Haftung der Leute:<br />
            Werden Schadenersatzansprüche aus außervertraglicher Haftung wegen Verlust oder Beschädigung des Umzugsgutes oder wegen Überschreitung der Lieferfrist gegen einen der Leute des Möbelspediteurs erhoben, so kann sich auch jener auf die Haftungsbefreiungen und -begrenzungen berufen. Das gilt auch, wenn er vorsätzlich oder leichtfertig und in dem Bewusstsein, dass ein Schaden mit Wahrscheinlichkeit eintreten werde, gehandelt hat.</p>
          <p>Ausführender Möbelspediteur:<br />
            Wird der Umzug ganz oder teilweise durch einen Dritten ausgeführt (ausführender Möbelspediteur), so haftet dieser für den Schaden, der durch den Verlust oder Beschädigung des Gutes oder durch Überschreitung der Lieferfrist während der durch ihn ausgeführten Beförderung entsteht, in gleicher Weise wie der Möbelspediteur. Der ausführende Möbelspediteur kann alle Einwendungen geltend machen, die dem Möbelspediteur aus dem Frachtvertrag zustehen. Möbelspediteur und ausführender Möbelspediteur haften als Gesamtschuldner. Werden Leute des ausführenden Möbelspediteurs in Anspruch genommen, so gelten für diese die Bestimmungen über Haftung der Leute.</p>
          <p>Haftungsvereinbarung:<br />
            Der Möbelspediteur weist den Absender auf die Möglichkeit hin, mit ihm gegen Bezahlung eines entsprechenden Entgeltes eine weitergehende als die gesetzlich vorgesehene Haftung zu vereinbaren.</p>
          <p>Transportversicherung:<br />
            Der Möbelspediteur weist den Absender auf die Möglichkeit hin, das Gut gegen Bezahlung einer besonderen Prämie zu versichern.</p>
          <p>Schadensanzeige:<br />
            Um das Erlöschen von Ersatzansprüchen zu verhindern, ist folgendes zu beachten. Der Absender ist verpflichtet, das Gut sofort bei Ablieferung auf äußerlich erkennbare Beschädigungen oder Verlust zu untersuchen. Diese sind auf dem Ablieferungsbeleg oder einem Schadensprotokoll spezifiziert festzuhalten und dem Möbelspediteur spätestens am Tag nach der Ablieferung anzuzeigen Äußerlich nicht erkennbare Beschädigungen oder Verluste, die der Absender erst beim Auspacken des Umzugsgutes feststellt, müssen dem Möbelspediteur innerhalb 14 Tagen nach Ablieferung spezifiziert angezeigt werden Pauschale Schadenanzeige genügen in keinem Fall Ansprüche wegen Überschreitung der Lieferfrist erlöschen wenn der Empfänger dem Möbelspediteur die Überschreitung nicht innerhalb von 14 Tagen nach Ablieferung anzeigt. Wird eine Anzeige nach Ablieferung erstattet, muss sie – um den Anspruchsverlust zu verhindern – in jedem Fall in schriftlicher Form und Innerhalb die vorgesehenen Fristen erfolgen Zur Wahrung der Fristen genügt die rechtzeitige Absendung</p>
          <p>Gefährliches Umzugsgut:<br />
            Zählt zu dem Umzugsgut gefährliches Gut (z.B. Benzin oder Öle), ist der Absender verpflichtet, dem Möbelspediteur rechtzeitig anzugeben welcher Natur die Gefahr ist, die von dem Gut ausgeht (z. B. Feuergefährlichkeit, ätzender Flüssigkeit, explosive Stoffe etc.)</p>
          <p>16. Rechtswahl<br />
            Es gilt deutsches Recht</p>
        </div>
      </div>
    </div>
  );
};

export default AgbPage;
